// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectotTUSBOLETOS.Context;

namespace ProyectotTUSBOLETOS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230725152219_Example")]
    partial class Example
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Evento", b =>
                {
                    b.Property<int>("PkEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Asientos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PkEvento");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Venta", b =>
                {
                    b.Property<int>("PkVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("FkEvento")
                        .HasColumnType("int");

                    b.Property<int?>("FkUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PkVenta");

                    b.HasIndex("FkEvento");

                    b.HasIndex("FkUsuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectotTUSBOLETOS.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ProyectotTUSBOLETOS.Entities.Venta", b =>
                {
                    b.HasOne("ProyectotTUSBOLETOS.Entities.Evento", "Eventos")
                        .WithMany()
                        .HasForeignKey("FkEvento");

                    b.HasOne("ProyectotTUSBOLETOS.Entities.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("FkUsuario");

                    b.Navigation("Eventos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
